# Generated by Django 3.1.7 on 2021-03-03 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20210303_0227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='stock_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fantasy_name', models.CharField(max_length=150, verbose_name='Nome Fantasia')),
                ('company_name', models.CharField(max_length=250, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('contact_email', models.EmailField(max_length=120, verbose_name='E-mail')),
                ('contact_phone', models.CharField(max_length=14, verbose_name='Telefone')),
                ('Street', models.CharField(max_length=220, verbose_name='Rua')),
                ('zipcode', models.CharField(max_length=9, verbose_name='Cep')),
                ('number', models.DecimalField(decimal_places=4, max_digits=4, max_length=4, verbose_name='Numero')),
                ('district', models.CharField(max_length=170, verbose_name='Bairro')),
                ('city', models.CharField(max_length=120, verbose_name='Cidade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'sellers',
            },
        ),
    ]
