# Generated by Django 3.1.7 on 2021-03-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210304_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='Street',
            new_name='street',
        ),
        migrations.AddField(
            model_name='marketplace',
            name='technical_manager',
            field=models.CharField(default=1, max_length=255, verbose_name='Responsável técnico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='uf',
            field=models.CharField(default=1, max_length=3, verbose_name='UF'),
            preserve_default=False,
        ),
    ]
