# Generated by Django 3.1.7 on 2021-03-05 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_seller_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketplace',
            name='product',
        ),
    ]
