# Generated by Django 3.1.7 on 2021-03-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_marketplace_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketplace',
            options={'verbose_name': 'Marketplace', 'verbose_name_plural': 'Marketplaces'},
        ),
        migrations.AlterModelOptions(
            name='seller',
            options={'verbose_name': 'Seller', 'verbose_name_plural': 'sellers'},
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='street',
            new_name='Address',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='uf',
        ),
        migrations.AddField(
            model_name='seller',
            name='state',
            field=models.CharField(default=1, max_length=3, verbose_name='Estado'),
            preserve_default=False,
        ),
    ]
